- hosts: all
  connection: local
  gather_facts: False


  vars_prompt:
      - name: "filter_regex"
        prompt: 'Enter your Contract name/sub-name'
        private: no
      - name: "tenant"
        prompt: 'Enter your Tenant name'
        private: no



  tasks:
    - name: Contract/Subject/Filter extract
      block:


       - include_tasks: login.yml


       - name: Collect Contracts
         uri:
           url: https://{{ inventory_hostname }}/api/node/mo/uni/tn-{{ tenant }}.json?query-target=children&target-subtree-class=vzBrCP&query-target=subtree&target-subtree-class=vzBrCP
           method: GET
           body_format: json
           return_content: yes
           headers:
             Cookie: "{{login.set_cookie}}"
           validate_certs: False
         no_log: True
         register: contracts


       - name: Fact - Contract match
         set_fact:
           contract_list: "{{ item.vzBrCP }}"
         no_log: True
         loop: "{{ contracts.json.imdata }}"
         when: 'item.vzBrCP.attributes.dn is search(filter_regex)'


       - name: Fail if Contract does not exist
         fail:
           msg: "Such contract does not exist"
         when: contract_list is not defined


       - name: Collect Subject > Filter mapping
         uri:
           url: https://{{ inventory_hostname }}/api/node/mo/{{ item.vzBrCP.attributes.dn }}.json?query-target=subtree&target-subtree-class=vzSubj&target-subtree-class=vzRsSubjFiltAtt,vzRsFiltAtt&query-target=subtree
           method: GET
           body_format: json
           return_content: no
           headers:
             Cookie: "{{login.set_cookie}}"
           validate_certs: False
          no_log: True
          loop: "{{ contracts.json.imdata }}"
         register: con_sub_fil
         when:
              - "item.vzBrCP.attributes.dn | regex_search(filter_regex)"
              - item.vzBrCP.attributes.dn is defined
         loop_control:
           pause: 0.2


       - name: Collect Contract to EPG Assignement
         uri:
           url: https://{{ inventory_hostname }}/api/node/mo/uni/tn-{{ tenant }}/brc-{{ item.vzBrCP.attributes.name }}.json?query-target=subtree&target-subtree-class=vzRtProv,vzRtCons,vzRtAnyToProv,vzRtAnyToCons
           method: GET
           body_format: json
           return_content: yes
           headers:
             Cookie: "{{login.set_cookie}}"
           validate_certs: False
         loop: "{{ contracts.json.imdata }}"
         no_log: True
         register: epg_contract
         when:
              - "item.vzBrCP.attributes.name | regex_search(filter_regex)"
              - item.vzBrCP.attributes.name is defined
         loop_control:
           pause: 0.2


       - name: Fact - regex for Contract > Subject > Filter mapping
         set_fact:
           Contract: "Contract Name: {{ item.item.vzBrCP.attributes.name }}"
           Subject: "Subject: {{ item.json | json_query('imdata[*].vzSubj.attributes.name') | join(' | ')  }}"
           Filters_Both_Dir: "Filters_Both_Dir: {{ item.json | json_query('imdata[*].vzRsSubjFiltAtt.attributes.tnVzFilterName') | join(' | ') }}"
           Filters_Non_Both_Dir: "Filters_Non_Both_Dir: {{ item.json | json_query('imdata[*].vzRsFiltAtt.attributes.tnVzFilterName') | join(' | ') }}"
         no_log: True
         loop: "{{ con_sub_fil.results }}"
         when: item.json is defined and item.item.vzBrCP is defined


       - name: Fact - regex for Contract > EPG
         set_fact:
           Contract: "Contract: {{ item.item.vzBrCP.attributes.name }}"
           EPG_AP_L3out_Consumed: "EPG_AP_L3out_Consumed: {{ item.json.imdata | json_query('[*].vzRtCons.attributes.tDn') | join(' | ') }}"
           EPG_AP_L3out_Provided: "EPG_AP_L3out_Provided: {{ item.json.imdata | json_query('[*].vzRtProv.attributes.tDn') | join(' | ') }}"
           VRF_VzAny_Consumed: "VRF_VzAny_Consumed: {{ item.json.imdata | json_query('[*].vzRtAnyToCons.attributes.tDn') | join(' | ') }}"
           VRF_VzAny_Provided: "VRF_VzAny_Provided: {{ item.json.imdata | json_query('[*].vzRtAnyToProv.attributes.tDn') | join(' | ') }}"
         no_log: True
         loop: "{{ epg_contract.results }}"
         when: item.json is defined


       - name: Banner Start
         debug:
           msg:
              - "-------------------------------------- STARTS HERE -----------------------------------------"
              - "-------------------------------------- STARTS HERE -----------------------------------------"
              - "-------------------------------------- STARTS HERE -----------------------------------------"
              - "-------------------------------------- STARTS HERE -----------------------------------------"
              - "-------------------------------------- STARTS HERE -----------------------------------------"
              - "-------------------------------------- STARTS HERE -----------------------------------------"
              - "-------------------------------------- STARTS HERE -----------------------------------------"
              - "-------------------------------------- STARTS HERE -----------------------------------------"
              - "-------------------------------------- STARTS HERE -----------------------------------------"



       - name: FINAL - output Contract > Subject > Filter mapping list
         debug:
           msg:
              - "{{ Contract }}"
              - "{{ Subject }}"
              - "{{ Filters_Both_Dir }}"
              - "{{ Filters_Non_Both_Dir }}"


       - name: Take a break ...
         pause:
            seconds: 120




       - name: FINAL - output Contract > EPG mapping list
         debug:
           msg:
              - "{{ Contract }}"
              - "{{ EPG_AP_L3out_Consumed }}"
              - "{{ EPG_AP_L3out_Provided }}"
              - "{{ VRF_VzAny_Consumed }}"
              - "{{ VRF_VzAny_Provided }}"



       - name: Banner End
         debug:
           msg:
              - "-------------------------------------- ENDS HERE ------------------------------------------"
              - "-------------------------------------- ENDS HERE ------------------------------------------"
              - "-------------------------------------- ENDS HERE ------------------------------------------"
              - "-------------------------------------- ENDS HERE ------------------------------------------"
              - "-------------------------------------- ENDS HERE ------------------------------------------"
              - "-------------------------------------- ENDS HERE ------------------------------------------"
              - "-------------------------------------- ENDS HERE ------------------------------------------"
              - "-------------------------------------- ENDS HERE ------------------------------------------"
              - "-------------------------------------- ENDS HERE ------------------------------------------"


       rescue:
         - name: Caught a general exception
           debug:
             msg:
                  - "GENERAL ERROR, try one of these methods:"
                  - "1.Verify login details"
                  - "2.APIC reachibility"
                  - "3.Run Ansible playbook with more verbose mode -vvv)"
